# Generated by Django 3.2 on 2023-03-26 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('program', models.CharField(blank=True, choices=[('lion cubs', 'Lion Cubs'), ('evolution academy', 'Evolution Academy'), ('evolution fusal club', 'Evolution Futsal Club')], max_length=50, null=True)),
                ('student_fname', models.CharField(max_length=50)),
                ('student_lname', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, default='2023-03-26', max_length=8, null=True)),
                ('gender', models.CharField(blank=True, choices=[('B', 'Boy'), ('G', 'Girl')], max_length=1, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=1000, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, null=True)),
                ('parent_fname', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('parent_lname', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('parent_email', models.EmailField(blank=True, default='', max_length=300, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="'(999) 999-9999'.", regex='^\\(?([0-9]{3})\\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$')])),
                ('emergency_fname', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_lname', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="'(999) 999-9999'.", regex='^\\(?([0-9]{3})\\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$')])),
                ('filled_out_fname', models.CharField(blank=True, max_length=50, null=True)),
                ('filled_out_lname', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
